// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nuages.PubSub.Storage.EntityFramework.MySql;

#nullable disable

namespace Nuages.PubSub.Storage.EntityFramework.MySql.Migrations
{
    [DbContext(typeof(MySqlPubSubDbContext))]
    partial class MySqlPubSubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nuages.PubSub.Storage.EntityFramework.DataModel.PubSubAck", b =>
                {
                    b.Property<string>("Hub")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AckId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Hub", "ConnectionId", "AckId");

                    b.ToTable("Acks");
                });

            modelBuilder.Entity("Nuages.PubSub.Storage.EntityFramework.DataModel.PubSubConnection", b =>
                {
                    b.Property<string>("Hub")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpireOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Permissions")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Hub", "ConnectionId");

                    b.HasIndex("Hub");

                    b.HasIndex("Hub", "UserId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("Nuages.PubSub.Storage.EntityFramework.DataModel.PubSubGroupConnection", b =>
                {
                    b.Property<string>("Hub")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpireOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Hub", "GroupName", "ConnectionId");

                    b.HasIndex("Hub", "GroupName");

                    b.ToTable("GroupConnections");
                });

            modelBuilder.Entity("Nuages.PubSub.Storage.EntityFramework.DataModel.PubSubGroupUser", b =>
                {
                    b.Property<string>("Hub")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Hub", "GroupName", "UserId");

                    b.HasIndex("Hub", "GroupName");

                    b.HasIndex("Hub", "UserId");

                    b.ToTable("GroupUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
